# Generated by Django 5.0.14 on 2026-06-11 23:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('host', 'Host'), ('ip', 'IP address'), ('domain', 'Domain'), ('webapp', 'Web application')], default='host', max_length=16)),
                ('internet_facing', models.BooleanField(default=False)),
                ('target', models.CharField(blank=True, help_text='Scannable target: hostname/IP/URL. Used by the Nuclei worker.', max_length=255)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('scanning_authorised', models.BooleanField(default=False, help_text='Written authorisation on file for active scanning of this estate.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('cve_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('in_kev', models.BooleanField(default=False)),
                ('kev_date_added', models.DateField(blank=True, null=True)),
                ('epss', models.FloatField(blank=True, null=True)),
                ('cvss', models.FloatField(blank=True, null=True)),
                ('cwe', models.CharField(blank=True, max_length=32)),
                ('affected', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('published', models.DateField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['in_kev'], name='core_cve_in_kev_66b5f3_idx'), models.Index(fields=['epss'], name='core_cve_epss_7c6f48_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('cpe', models.CharField(blank=True, max_length=400)),
                ('source', models.CharField(blank=True, help_text='Where this inventory row came from: trmm, action1, manual, wazuh.', max_length=50)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='WatchSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('product', models.CharField(blank=True, max_length=200)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('P1', 'P1 — Critical (KEV)'), ('P2', 'P2 — High (likely exploited / exposed)'), ('P3', 'P3 — Medium'), ('P4', 'P4 — Low'), ('P?', 'P? — Needs human review')], default='P?', max_length=2)),
                ('status', models.CharField(choices=[('open', 'Open'), ('triaged', 'Triaged'), ('fixed', 'Fixed'), ('accepted', 'Risk accepted')], default='open', max_length=10)),
                ('match_confidence', models.CharField(blank=True, max_length=10)),
                ('match_reason', models.CharField(blank=True, max_length=300)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.asset')),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.cve')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='core.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.tenant')),
            ],
            options={
                'ordering': ['priority', '-cve__epss'],
                'unique_together': {('asset', 'cve', 'product')},
            },
        ),
    ]
