# Generated by Django 5.0.14 on 2026-06-12 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finding',
            options={'ordering': ['priority']},
        ),
        migrations.AlterUniqueTogether(
            name='finding',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='finding',
            name='matched_at',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='finding',
            name='severity',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='finding',
            name='source',
            field=models.CharField(default='watch', max_length=16),
        ),
        migrations.AddField(
            model_name='finding',
            name='template_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='finding',
            name='title',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='finding',
            name='cve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.cve'),
        ),
    ]
