# Generated by Django 5.0.14 on 2026-06-12 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_finding_options_alter_finding_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CveProductToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tokens', to='core.cve')),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='core_cvepro_token_302a47_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cveproducttoken',
            constraint=models.UniqueConstraint(fields=('cve', 'token'), name='uniq_cve_token'),
        ),
    ]
