# Generated by Django 5.0.14 on 2026-06-12 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scanjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='scan_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='core.scanjob'),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='phase',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
