# Generated by Django 5.0.14 on 2026-06-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_finding_scan_job_scanjob_phase_scanjob_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='finding',
            name='references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='finding',
            name='remediation',
            field=models.TextField(blank=True),
        ),
    ]
