# Generated by Django 5.0.14 on 2026-06-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cve_references_finding_references_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='tenant',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
