# Generated by Django 5.0.14 on 2026-06-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_asset_external_id_tenant_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_health_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(blank=True, default='', help_text='online / offline / unknown, per last SynthOps health check.', max_length=16),
        ),
    ]
