# Generated by Django 5.0.14 on 2026-06-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_asset_tactical_rmm_agent_id_remediationaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediationaction',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('timeout', 'Timed out — outcome unknown')], default='queued', max_length=10),
        ),
    ]
