# Generated by Django 5.0.14 on 2026-06-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_suppression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='in_kev',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['priority', 'cve'], name='core_findin_priorit_134b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['tenant', 'priority', 'cve'], name='core_findin_tenant__1fabc2_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['cve', 'asset'], name='core_findin_cve_id_aec684_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['source', 'last_seen'], name='core_findin_source_e81470_idx'),
        ),
    ]
