# Generated by Django 5.0.14 on 2026-06-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_cve_in_kev_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='auto_update_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
