# Generated by Django 5.0.14 on 2026-06-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_finding_auto_update_failed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fix_source',
            field=models.CharField(choices=[('unknown', 'Not yet probed'), ('winget', 'winget'), ('choco', 'Chocolatey'), ('none', 'No package-manager fix')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='fix_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='probed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
