# Generated by Django 5.0.14 on 2026-06-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_fix_source_product_fix_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='local_ip',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='asset',
            name='public_ip',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
