# Generated by Django 5.0.14 on 2026-06-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_asset_local_ip_asset_public_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='open_ports',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
